/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CvRouteImport } from './routes/cv'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MisCvRouteImport } from './routes/mis-cv'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PostulacionesRouteImport } from './routes/postulaciones'
import { Route as PostulacionesIndexRouteImport } from './routes/postulaciones.index'
import { Route as PostulacionesIdRouteImport } from './routes/postulaciones.$id'
import { Route as PostulacionesNuevaRouteImport } from './routes/postulaciones.nueva'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MisCvRoute = MisCvRouteImport.update({
  id: '/mis-cv',
  path: '/mis-cv',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PostulacionesRoute = PostulacionesRouteImport.update({
  id: '/postulaciones',
  path: '/postulaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const PostulacionesIndexRoute = PostulacionesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostulacionesRoute,
} as any)
const PostulacionesIdRoute = PostulacionesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PostulacionesRoute,
} as any)
const PostulacionesNuevaRoute = PostulacionesNuevaRouteImport.update({
  id: '/nueva',
  path: '/nueva',
  getParentRoute: () => PostulacionesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/login': typeof LoginRoute
  '/mis-cv': typeof MisCvRoute
  '/perfil': typeof PerfilRoute
  '/postulaciones': typeof PostulacionesRouteWithChildren
  '/postulaciones/$id': typeof PostulacionesIdRoute
  '/postulaciones/nueva': typeof PostulacionesNuevaRoute
  '/postulaciones/': typeof PostulacionesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/login': typeof LoginRoute
  '/mis-cv': typeof MisCvRoute
  '/perfil': typeof PerfilRoute
  '/postulaciones/$id': typeof PostulacionesIdRoute
  '/postulaciones/nueva': typeof PostulacionesNuevaRoute
  '/postulaciones': typeof PostulacionesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/login': typeof LoginRoute
  '/mis-cv': typeof MisCvRoute
  '/perfil': typeof PerfilRoute
  '/postulaciones': typeof PostulacionesRouteWithChildren
  '/postulaciones/$id': typeof PostulacionesIdRoute
  '/postulaciones/nueva': typeof PostulacionesNuevaRoute
  '/postulaciones/': typeof PostulacionesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cv'
    | '/login'
    | '/mis-cv'
    | '/perfil'
    | '/postulaciones'
    | '/postulaciones/$id'
    | '/postulaciones/nueva'
    | '/postulaciones/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cv'
    | '/login'
    | '/mis-cv'
    | '/perfil'
    | '/postulaciones/$id'
    | '/postulaciones/nueva'
    | '/postulaciones'
  id:
    | '__root__'
    | '/'
    | '/cv'
    | '/login'
    | '/mis-cv'
    | '/perfil'
    | '/postulaciones'
    | '/postulaciones/$id'
    | '/postulaciones/nueva'
    | '/postulaciones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CvRoute: typeof CvRoute
  LoginRoute: typeof LoginRoute
  MisCvRoute: typeof MisCvRoute
  PerfilRoute: typeof PerfilRoute
  PostulacionesRoute: typeof PostulacionesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-cv': {
      id: '/mis-cv'
      path: '/mis-cv'
      fullPath: '/mis-cv'
      preLoaderRoute: typeof MisCvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postulaciones': {
      id: '/postulaciones'
      path: '/postulaciones'
      fullPath: '/postulaciones'
      preLoaderRoute: typeof PostulacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postulaciones/': {
      id: '/postulaciones/'
      path: '/'
      fullPath: '/postulaciones/'
      preLoaderRoute: typeof PostulacionesIndexRouteImport
      parentRoute: typeof PostulacionesRoute
    }
    '/postulaciones/$id': {
      id: '/postulaciones/$id'
      path: '/$id'
      fullPath: '/postulaciones/$id'
      preLoaderRoute: typeof PostulacionesIdRouteImport
      parentRoute: typeof PostulacionesRoute
    }
    '/postulaciones/nueva': {
      id: '/postulaciones/nueva'
      path: '/nueva'
      fullPath: '/postulaciones/nueva'
      preLoaderRoute: typeof PostulacionesNuevaRouteImport
      parentRoute: typeof PostulacionesRoute
    }
  }
}

interface PostulacionesRouteChildren {
  PostulacionesIdRoute: typeof PostulacionesIdRoute
  PostulacionesNuevaRoute: typeof PostulacionesNuevaRoute
  PostulacionesIndexRoute: typeof PostulacionesIndexRoute
}

const PostulacionesRouteChildren: PostulacionesRouteChildren = {
  PostulacionesIdRoute: PostulacionesIdRoute,
  PostulacionesNuevaRoute: PostulacionesNuevaRoute,
  PostulacionesIndexRoute: PostulacionesIndexRoute,
}

const PostulacionesRouteWithChildren = PostulacionesRoute._addFileChildren(
  PostulacionesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CvRoute: CvRoute,
  LoginRoute: LoginRoute,
  MisCvRoute: MisCvRoute,
  PerfilRoute: PerfilRoute,
  PostulacionesRoute: PostulacionesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
