/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedCvRouteImport } from './routes/_authenticated/cv'
import { Route as AuthenticatedMisCvRouteImport } from './routes/_authenticated/mis-cv'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPostulacionesRouteImport } from './routes/_authenticated/postulaciones'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthGmailCallbackRouteImport } from './routes/auth.gmail-callback'
import { Route as AuthenticatedPostulacionesIndexRouteImport } from './routes/_authenticated/postulaciones.index'
import { Route as AuthenticatedPostulacionesIdRouteImport } from './routes/_authenticated/postulaciones.$id'
import { Route as AuthenticatedPostulacionesNuevaRouteImport } from './routes/_authenticated/postulaciones.nueva'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCvRoute = AuthenticatedCvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMisCvRoute = AuthenticatedMisCvRouteImport.update({
  id: '/mis-cv',
  path: '/mis-cv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPostulacionesRoute =
  AuthenticatedPostulacionesRouteImport.update({
    id: '/postulaciones',
    path: '/postulaciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGmailCallbackRoute = AuthGmailCallbackRouteImport.update({
  id: '/auth/gmail-callback',
  path: '/auth/gmail-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPostulacionesIndexRoute =
  AuthenticatedPostulacionesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPostulacionesRoute,
  } as any)
const AuthenticatedPostulacionesIdRoute =
  AuthenticatedPostulacionesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPostulacionesRoute,
  } as any)
const AuthenticatedPostulacionesNuevaRoute =
  AuthenticatedPostulacionesNuevaRouteImport.update({
    id: '/nueva',
    path: '/nueva',
    getParentRoute: () => AuthenticatedPostulacionesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cv': typeof AuthenticatedCvRoute
  '/mis-cv': typeof AuthenticatedMisCvRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/postulaciones': typeof AuthenticatedPostulacionesRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/gmail-callback': typeof AuthGmailCallbackRoute
  '/postulaciones/$id': typeof AuthenticatedPostulacionesIdRoute
  '/postulaciones/nueva': typeof AuthenticatedPostulacionesNuevaRoute
  '/postulaciones/': typeof AuthenticatedPostulacionesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cv': typeof AuthenticatedCvRoute
  '/mis-cv': typeof AuthenticatedMisCvRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/gmail-callback': typeof AuthGmailCallbackRoute
  '/postulaciones/$id': typeof AuthenticatedPostulacionesIdRoute
  '/postulaciones/nueva': typeof AuthenticatedPostulacionesNuevaRoute
  '/postulaciones': typeof AuthenticatedPostulacionesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/cv': typeof AuthenticatedCvRoute
  '/_authenticated/mis-cv': typeof AuthenticatedMisCvRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/postulaciones': typeof AuthenticatedPostulacionesRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/gmail-callback': typeof AuthGmailCallbackRoute
  '/_authenticated/postulaciones/$id': typeof AuthenticatedPostulacionesIdRoute
  '/_authenticated/postulaciones/nueva': typeof AuthenticatedPostulacionesNuevaRoute
  '/_authenticated/postulaciones/': typeof AuthenticatedPostulacionesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/cv'
    | '/mis-cv'
    | '/perfil'
    | '/postulaciones'
    | '/auth/callback'
    | '/auth/gmail-callback'
    | '/postulaciones/$id'
    | '/postulaciones/nueva'
    | '/postulaciones/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/cv'
    | '/mis-cv'
    | '/perfil'
    | '/auth/callback'
    | '/auth/gmail-callback'
    | '/postulaciones/$id'
    | '/postulaciones/nueva'
    | '/postulaciones'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/cv'
    | '/_authenticated/mis-cv'
    | '/_authenticated/perfil'
    | '/_authenticated/postulaciones'
    | '/auth/callback'
    | '/auth/gmail-callback'
    | '/_authenticated/postulaciones/$id'
    | '/_authenticated/postulaciones/nueva'
    | '/_authenticated/postulaciones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthGmailCallbackRoute: typeof AuthGmailCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cv': {
      id: '/_authenticated/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof AuthenticatedCvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mis-cv': {
      id: '/_authenticated/mis-cv'
      path: '/mis-cv'
      fullPath: '/mis-cv'
      preLoaderRoute: typeof AuthenticatedMisCvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/postulaciones': {
      id: '/_authenticated/postulaciones'
      path: '/postulaciones'
      fullPath: '/postulaciones'
      preLoaderRoute: typeof AuthenticatedPostulacionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/gmail-callback': {
      id: '/auth/gmail-callback'
      path: '/auth/gmail-callback'
      fullPath: '/auth/gmail-callback'
      preLoaderRoute: typeof AuthGmailCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/postulaciones/': {
      id: '/_authenticated/postulaciones/'
      path: '/'
      fullPath: '/postulaciones/'
      preLoaderRoute: typeof AuthenticatedPostulacionesIndexRouteImport
      parentRoute: typeof AuthenticatedPostulacionesRoute
    }
    '/_authenticated/postulaciones/$id': {
      id: '/_authenticated/postulaciones/$id'
      path: '/$id'
      fullPath: '/postulaciones/$id'
      preLoaderRoute: typeof AuthenticatedPostulacionesIdRouteImport
      parentRoute: typeof AuthenticatedPostulacionesRoute
    }
    '/_authenticated/postulaciones/nueva': {
      id: '/_authenticated/postulaciones/nueva'
      path: '/nueva'
      fullPath: '/postulaciones/nueva'
      preLoaderRoute: typeof AuthenticatedPostulacionesNuevaRouteImport
      parentRoute: typeof AuthenticatedPostulacionesRoute
    }
  }
}

interface AuthenticatedPostulacionesRouteChildren {
  AuthenticatedPostulacionesIdRoute: typeof AuthenticatedPostulacionesIdRoute
  AuthenticatedPostulacionesNuevaRoute: typeof AuthenticatedPostulacionesNuevaRoute
  AuthenticatedPostulacionesIndexRoute: typeof AuthenticatedPostulacionesIndexRoute
}

const AuthenticatedPostulacionesRouteChildren: AuthenticatedPostulacionesRouteChildren =
  {
    AuthenticatedPostulacionesIdRoute: AuthenticatedPostulacionesIdRoute,
    AuthenticatedPostulacionesNuevaRoute: AuthenticatedPostulacionesNuevaRoute,
    AuthenticatedPostulacionesIndexRoute: AuthenticatedPostulacionesIndexRoute,
  }

const AuthenticatedPostulacionesRouteWithChildren =
  AuthenticatedPostulacionesRoute._addFileChildren(
    AuthenticatedPostulacionesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCvRoute: typeof AuthenticatedCvRoute
  AuthenticatedMisCvRoute: typeof AuthenticatedMisCvRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPostulacionesRoute: typeof AuthenticatedPostulacionesRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCvRoute: AuthenticatedCvRoute,
  AuthenticatedMisCvRoute: AuthenticatedMisCvRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPostulacionesRoute: AuthenticatedPostulacionesRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthGmailCallbackRoute: AuthGmailCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
